---
label: Theme configuration
hide_body: true
fields:
- type: text
  name: site_name
  label: Site name
- type: textarea
  name: site_description
  label: Site description
- type: textarea
  name: hero_title
  label: Hero title
  config:
    wysiwyg: true
    schema:
      format: html
- type: textarea
  name: hero_subtitle
  label: Hero subtitle
  config:
    wysiwyg: true
    schema:
      format: html
- name: footer
  label: Footer text
  type: text
  hidden: false
  default: ''
- type: boolean
  name: dark_mode
  label: Dark mode
- name: font_display
  type: select
  default: []
  config:
    required: false
    options:
    - CenturyGothic
    - OpenSans
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Font Display
  description: The font to be used for headers
- name: font_body
  type: select
  default: []
  config:
    required: false
    options:
    - CenturyGothic
    - OpenSans
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Font Body
  description: The font to be used for body paragraphs
pages:
- data/theme.json
